# Generated by Django 3.2.9 on 2021-11-17 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolistitem',
            name='isCompleted',
            field=models.BooleanField(default=False),
        ),
    ]
