# Generated by Django 3.2.9 on 2021-11-19 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_todolistitem_iscompleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolistitem',
            name='beingEdited',
            field=models.BooleanField(default=False),
        ),
    ]
